@Library('shared-lib@main') _

def SERVICE = "user-service"
def PORT = "8081"

pipeline {
    agent any

    stages {
        stage('Checkout') { steps { gitCheckout() } }
        stage('Build') { steps { buildDocker(SERVICE) } }
        stage('Run') { steps { runDocker(SERVICE, PORT) } }
    }
}