@Library('shared-lib@main') _

pipeline {
    agent any

    environment {
        SERVICE_NAME = "user-service"
        IMAGE_NAME = "user-service"
        PORT = "8081"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dockerBuild(IMAGE_NAME, "services/UserService/Dockerfile", ".")
            }
        }

        stage('Run') {
            steps {
                dockerRun(SERVICE_NAME, IMAGE_NAME, PORT)
            }
        }
    }
}