FROM golang:1.25.3-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest && \
    go install github.com/pressly/goose/v3/cmd/goose@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8081 50051

CMD ["air", "-c", "services/UserService/.air.toml"]