FROM golang:1.25.3-alpine

WORKDIR /app

# تثبيت الأدوات اللازمة
RUN go install github.com/air-verse/air@latest && \
    go install github.com/pressly/goose/v3/cmd/goose@latest

# نسخ ملفات الـ modules أولاً لتسريع الـ Cache
COPY go.mod go.sum ./
RUN go mod download

# نسخ المشروع بالكامل
COPY . .

# المنفذ الخاص بالـ gRPC والـ HTTP
EXPOSE 8081 50051

# تشغيل Air مع ملف الإعدادات الخاص بالخدمة
CMD ["air", "-c", "services/UserService/.air.toml"]