@Library('ecommerce-shared-lib') _

def SERVICE = "cart-service"
def PORT = "8082"

pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                gitCheckout()
            }
        }

        stage('Build') {
            steps {
                buildDocker(SERVICE)
            }
        }

        stage('Run') {
            steps {
                runDocker(SERVICE, PORT)
            }
        }

    }

    post {
        success {
            notify("SUCCESS", SERVICE)
        }
        failure {
            notify("FAILED", SERVICE)
        }
    }
}