@Library('shared-lib') _

pipeline {
    agent any

    environment {
        SERVICE_NAME = "cart-service"
        IMAGE_NAME = "cart-service"
        PORT = "8082"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dockerBuild(IMAGE_NAME, "services/CartService/Dockerfile", ".")
            }
        }

        stage('Run') {
            steps {
                dockerRun(SERVICE_NAME, IMAGE_NAME, PORT)
            }
        }
    }
}