apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-service-config
  namespace: ecommerce
data:
  REDIS_HOST: cart-redis
  REDIS_PORT: "6379"

  GRPC_PORT: "50057"
  APP_PORT: "8082"

  USER_SERVICE_GRPC_ADDR: user-service.ecommerce.svc.cluster.local:50051
  PRODUCT_SERVICE_GRPC_ADDR: product-service.ecommerce.svc.cluster.local:50053

  SERVICE_NAME: cart-service
  APP_ENV: production