apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-postgres-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: user-postgres-sc
  resources:
    requests:
      storage: 5Gi