FROM golang:1.25.3-alpine

WORKDIR /app

# Install air for hot reload and goose for migrations
RUN go install github.com/air-verse/air@latest && \
    go install github.com/pressly/goose/v3/cmd/goose@latest

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy the entire project
COPY . .

EXPOSE 8000

# Use air for hot reload
CMD ["/go/bin/air", "-c", "./services/ApiGateway/.air.toml"]
