apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-redis
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-redis

  template:
    metadata:
      labels:
        app: product-redis

    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379