apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: ecommerce
data:
  APP_PORT: "8000"
  APP_ENV: "production"
  SERVICE_NAME: api-gateway

  USER_SERVICE_URL: user-service:50051
  PRODUCT_SERVICE_URL: product-service:50053
  CART_SERVICE_URL: cart-service:50057
  ORDER_SERVICE_URL: order-service:50055

  CB_ENABLED: "true"
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW_SECONDS: "60"

  ALLOWED_ORIGINS: "*"
  ALLOWED_METHODS: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  ALLOWED_HEADERS: "Accept,Authorization,Content-Type,X-Request-ID"