apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecommerce
spec:
  replicas: 2

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
        - name: product-service
          image: mohamedashraf001/product-service:latest

          ports:
            - containerPort: 50053

          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secret

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"