FROM golang:1.25.3-alpine

# تثبيت الأدوات الأساسية
RUN apk add --no-cache curl git build-base

# العنوان الجديد للأداة (Air-verse)
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# إعدادات الموديولز
ENV GO111MODULE=on
ENV GOPROXY=https://proxy.golang.org,direct

# نسخ ملفات الموديولز
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 50053 8080

CMD ["air", "-c", "services/ProductService/.air.toml"]