apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: product-postgres-sc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/product-postgres